# Generated by Django 3.0.8 on 2020-09-09 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_role'),
        ('main_app', '0002_admin_appointment_conditions_proscriptions'),
    ]

    operations = [
    ]
