# Generated by Django 3.1 on 2020-09-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_merge_20200909_1605'),
        ('main_app', '0003_auto_20200909_1257'),
    ]

    operations = [
    ]
