# Generated by Django 3.1 on 2020-09-11 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_patientuserprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoruserprofile',
            name='phone_number',
            field=models.CharField(default='Enter Number', max_length=15),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='address',
            field=models.TextField(default='Enter Address', max_length=200),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='age',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='date_of_birth',
            field=models.CharField(default='day/month/year', max_length=30),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='emergency_contact',
            field=models.CharField(default='Enter Name', max_length=100),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='emergency_number',
            field=models.CharField(default='Enter Number', max_length=15),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='emergency_relation',
            field=models.CharField(default='Enter Relationship', max_length=50),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='health_card_number',
            field=models.CharField(default='Enter Number', max_length=15),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='height',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='phone_number',
            field=models.CharField(default='Enter Number', max_length=15),
        ),
        migrations.AddField(
            model_name='patientuserprofile',
            name='weight',
            field=models.IntegerField(default=10),
        ),
    ]
