# Generated by Django 3.1 on 2020-09-11 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200910_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Day of the event', verbose_name='Day of the event')),
                ('start_time', models.TimeField(help_text='Starting time', verbose_name='Starting time')),
                ('end_time', models.TimeField(help_text='Final time', verbose_name='Final time')),
                ('notes', models.TextField(blank=True, help_text='Appointment details', null=True, verbose_name='Appointment details')),
                ('doctor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.doctoruserprofile')),
                ('patient', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.patientuserprofile')),
            ],
            options={
                'verbose_name': 'Apopointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
        migrations.RemoveField(
            model_name='conditions',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Conditions',
        ),
    ]
