# Generated by Django 3.1 on 2020-09-11 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200910_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnote',
            name='dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
